# Generated by Django 4.1.7 on 2023-04-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='desicription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='desicription',
            new_name='description',
        ),
    ]
