# Generated by Django 4.1.7 on 2023-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_desicription_movies_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
