# Generated by Django 4.1.7 on 2023-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movies_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='description',
        ),
        migrations.AddField(
            model_name='tvshows',
            name='trailer',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
