# Generated by Django 4.1.7 on 2023-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_movies_description_remove_tvshows_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
