# Generated by Django 4.1.7 on 2023-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_movies_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
