# Generated by Django 4.1.7 on 2023-04-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tvshows_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='rating',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
