# Generated by Django 4.1.7 on 2023-04-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tvshows_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshows',
            name='description',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
