# Generated by Django 4.1.7 on 2023-04-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_tvshows_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshows',
            old_name='budget',
            new_name='tbudget',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='details',
            new_name='tdetails',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='name',
            new_name='tname',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='poster',
            new_name='tposter',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='rating',
            new_name='trating',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='trailer',
            new_name='ttrailer',
        ),
    ]
