# Generated by Django 4.1.7 on 2023-04-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_budget_tvshows_tbudget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshows',
            old_name='tbudget',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='tdetails',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='tname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='tposter',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='trating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='ttrailer',
            new_name='trailer',
        ),
    ]
